version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: prjExcursionistas  # Nome do banco de dados
      MYSQL_ROOT_PASSWORD: 132969        # Senha do usuário root
      MYSQL_USER: lamego                 # Nome do outro usuário (se necessário)
      MYSQL_PASSWORD: 132969             # Senha do usuário 'lamego' (se necessário)
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql  # Volume persistente para dados
    ports:
      - "3300:3306"
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - laravel

  app:
    build:
      context: .  # Diretório onde está o Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html/prjExcursionistas
    networks:
      - laravel

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
